<?php

namespace Database\Seeders;

use App\Models\Branch;
use App\Models\ComputerAsset;
use App\Models\Node;
use Illuminate\Database\Seeder;

class TenantInventorySeeder extends Seeder
{
    public function run(): void
    {
        $branches = Branch::query()->get()->keyBy('name');
        $nodes = Node::query()->get()->keyBy('name');

        $assets = [
            [
                'branch' => 'Campus Central',
                'node' => null,
                'equipment_type' => 'desktop',
                'asset_tag' => 'CMP-CDMX-001',
                'hostname' => 'PC-FIN-CDMX-01',
                'assigned_user' => 'Mariana Soto',
                'brand' => 'Dell',
                'model' => 'OptiPlex 7010',
                'serial_number' => 'DL-CMX-7010-001',
                'cpu' => 'Intel Core i7-13700',
                'ram_gb' => 32,
                'storage_type' => 'ssd',
                'storage_gb' => 1024,
                'operating_system' => 'Windows 11 Pro',
                'office_version' => 'Microsoft 365 Apps',
                'purchase_date' => '2025-01-15',
                'warranty_expires_at' => '2028-01-15',
                'status' => 'in_use',
                'notes' => 'Equipo de analista financiero.',
                'details' => ['department' => 'Finanzas', 'location' => 'Piso 2', 'ups' => true],
            ],
            [
                'branch' => 'Campus Central',
                'node' => null,
                'equipment_type' => 'monitor',
                'asset_tag' => 'MON-CDMX-001',
                'hostname' => null,
                'assigned_user' => 'Mariana Soto',
                'brand' => 'LG',
                'model' => '27UP650',
                'serial_number' => 'LG-27U-001',
                'cpu' => null,
                'ram_gb' => null,
                'storage_type' => null,
                'storage_gb' => null,
                'operating_system' => null,
                'office_version' => null,
                'purchase_date' => '2025-01-15',
                'warranty_expires_at' => '2027-01-15',
                'status' => 'in_use',
                'notes' => 'Monitor principal de estación financiera.',
                'details' => ['size_inches' => 27, 'resolution' => '4K', 'connector' => 'USB-C'],
            ],
            [
                'branch' => 'Campus Central',
                'node' => null,
                'equipment_type' => 'headset',
                'asset_tag' => 'DIA-CDMX-001',
                'hostname' => null,
                'assigned_user' => 'Mesa de ayuda',
                'brand' => 'Jabra',
                'model' => 'Evolve2 40',
                'serial_number' => 'JABRA-001',
                'cpu' => null,
                'ram_gb' => null,
                'storage_type' => null,
                'storage_gb' => null,
                'operating_system' => null,
                'office_version' => null,
                'purchase_date' => '2025-02-10',
                'warranty_expires_at' => '2027-02-10',
                'status' => 'in_use',
                'notes' => 'Diadema para soporte L1.',
                'details' => ['noise_cancelling' => true, 'connection' => 'USB-A'],
            ],
            [
                'branch' => 'Campus Central',
                'node' => null,
                'equipment_type' => 'phone',
                'asset_tag' => 'TEL-CDMX-001',
                'hostname' => null,
                'assigned_user' => 'Recepción Central',
                'brand' => 'Yealink',
                'model' => 'T54W',
                'serial_number' => 'YEA-T54W-001',
                'cpu' => null,
                'ram_gb' => null,
                'storage_type' => null,
                'storage_gb' => null,
                'operating_system' => null,
                'office_version' => null,
                'purchase_date' => '2025-01-05',
                'warranty_expires_at' => '2027-01-05',
                'status' => 'in_use',
                'notes' => 'Teléfono IP de recepción.',
                'details' => ['extension' => '1001', 'line_type' => 'VoIP', 'poe' => true],
            ],
            [
                'branch' => 'Campus Norte',
                'node' => null,
                'equipment_type' => 'laptop',
                'asset_tag' => 'LAP-MTY-001',
                'hostname' => 'LT-VEN-MTY-01',
                'assigned_user' => 'Iván Cárdenas',
                'brand' => 'Lenovo',
                'model' => 'ThinkPad T14 Gen 5',
                'serial_number' => 'LNV-MTY-T14-01',
                'cpu' => 'Intel Core Ultra 7',
                'ram_gb' => 16,
                'storage_type' => 'nvme',
                'storage_gb' => 512,
                'operating_system' => 'Windows 11 Pro',
                'office_version' => 'Microsoft 365 Apps',
                'purchase_date' => '2025-03-20',
                'warranty_expires_at' => '2028-03-20',
                'status' => 'in_use',
                'notes' => 'Equipo de gerente comercial.',
                'details' => ['department' => 'Ventas', 'docking_station' => true, 'travel_case' => true],
            ],
            [
                'branch' => 'Campus Norte',
                'node' => null,
                'equipment_type' => 'monitor',
                'asset_tag' => 'MON-MTY-002',
                'hostname' => null,
                'assigned_user' => 'Iván Cárdenas',
                'brand' => 'Samsung',
                'model' => 'S27A600U',
                'serial_number' => 'SMS-MTY-27-02',
                'cpu' => null,
                'ram_gb' => null,
                'storage_type' => null,
                'storage_gb' => null,
                'operating_system' => null,
                'office_version' => null,
                'purchase_date' => '2025-03-20',
                'warranty_expires_at' => '2027-03-20',
                'status' => 'in_use',
                'notes' => 'Monitor para estación híbrida.',
                'details' => ['size_inches' => 27, 'resolution' => 'QHD', 'connector' => 'DisplayPort'],
            ],
            [
                'branch' => 'Campus Norte',
                'node' => null,
                'equipment_type' => 'phone',
                'asset_tag' => 'TEL-MTY-010',
                'hostname' => null,
                'assigned_user' => 'Sala de juntas Norte',
                'brand' => 'Cisco',
                'model' => '8845',
                'serial_number' => 'CSC-MTY-8845-10',
                'cpu' => null,
                'ram_gb' => null,
                'storage_type' => null,
                'storage_gb' => null,
                'operating_system' => null,
                'office_version' => null,
                'purchase_date' => '2025-04-02',
                'warranty_expires_at' => '2028-04-02',
                'status' => 'in_use',
                'notes' => 'Teléfono de videoconferencia para juntas.',
                'details' => ['extension' => '2104', 'line_type' => 'VoIP', 'camera' => true],
            ],
            [
                'branch' => 'Campus Norte',
                'node' => null,
                'equipment_type' => 'desktop',
                'asset_tag' => 'CMP-MTY-009',
                'hostname' => 'PC-RH-MTY-09',
                'assigned_user' => 'Laura Mena',
                'brand' => 'HP',
                'model' => 'EliteDesk 800 G9',
                'serial_number' => 'HP-MTY-ED-009',
                'cpu' => 'Intel Core i5-14500',
                'ram_gb' => 16,
                'storage_type' => 'ssd',
                'storage_gb' => 512,
                'operating_system' => 'Windows 11 Pro',
                'office_version' => 'Microsoft 365 Apps',
                'purchase_date' => '2024-11-14',
                'warranty_expires_at' => '2027-11-14',
                'status' => 'repair',
                'notes' => 'Pendiente cambio de fuente de poder.',
                'details' => ['department' => 'RH', 'incident' => 'No energiza', 'ticket' => 'HD-24119'],
            ],
            [
                'branch' => 'Campus Norte',
                'node' => null,
                'equipment_type' => 'headset',
                'asset_tag' => 'DIA-MTY-021',
                'hostname' => null,
                'assigned_user' => 'Contact Center Norte',
                'brand' => 'Logitech',
                'model' => 'Zone Wired',
                'serial_number' => 'LOG-MTY-ZW-21',
                'cpu' => null,
                'ram_gb' => null,
                'storage_type' => null,
                'storage_gb' => null,
                'operating_system' => null,
                'office_version' => null,
                'purchase_date' => '2024-09-08',
                'warranty_expires_at' => '2026-09-08',
                'status' => 'repair',
                'notes' => 'Micrófono intermitente.',
                'details' => ['noise_cancelling' => true, 'connection' => 'USB-C', 'ticket' => 'HD-24567'],
            ],
            [
                'branch' => 'Campus Occidente',
                'node' => null,
                'equipment_type' => 'monitor',
                'asset_tag' => 'MON-GDL-031',
                'hostname' => null,
                'assigned_user' => 'Bodega TI',
                'brand' => 'Dell',
                'model' => 'P2422H',
                'serial_number' => 'DLL-GDL-P24-31',
                'cpu' => null,
                'ram_gb' => null,
                'storage_type' => null,
                'storage_gb' => null,
                'operating_system' => null,
                'office_version' => null,
                'purchase_date' => '2025-01-30',
                'warranty_expires_at' => '2028-01-30',
                'status' => 'stock',
                'notes' => 'Disponible para reposición.',
                'details' => ['size_inches' => 24, 'resolution' => 'FHD', 'connector' => 'HDMI'],
            ],
            [
                'branch' => 'Campus Occidente',
                'node' => null,
                'equipment_type' => 'phone',
                'asset_tag' => 'TEL-GDL-018',
                'hostname' => null,
                'assigned_user' => 'Almacén TI',
                'brand' => 'Grandstream',
                'model' => 'GRP2612',
                'serial_number' => 'GST-GDL-2612-18',
                'cpu' => null,
                'ram_gb' => null,
                'storage_type' => null,
                'storage_gb' => null,
                'operating_system' => null,
                'office_version' => null,
                'purchase_date' => '2023-06-18',
                'warranty_expires_at' => '2025-06-18',
                'status' => 'retired',
                'notes' => 'Retirado por renovación de telefonía.',
                'details' => ['extension' => '3108', 'line_type' => 'VoIP', 'retirement_reason' => 'Obsolescencia'],
            ],
            [
                'branch' => 'Campus Central',
                'node' => null,
                'equipment_type' => 'laptop',
                'asset_tag' => 'LAP-CDMX-014',
                'hostname' => 'LT-MKT-CDMX-14',
                'assigned_user' => 'Daniela Cruz',
                'brand' => 'Apple',
                'model' => 'MacBook Pro 14',
                'serial_number' => 'APL-CDMX-MBP14-14',
                'cpu' => 'Apple M3 Pro',
                'ram_gb' => 18,
                'storage_type' => 'ssd',
                'storage_gb' => 1024,
                'operating_system' => 'macOS Sequoia',
                'office_version' => 'Microsoft 365 for Mac',
                'purchase_date' => '2025-02-12',
                'warranty_expires_at' => '2028-02-12',
                'status' => 'stock',
                'notes' => 'Equipo disponible para nueva incorporación del área de marketing.',
                'details' => ['department' => 'Marketing', 'pool' => 'onboarding', 'charger' => 'USB-C 96W'],
            ],
            [
                'branch' => 'Campus Central',
                'node' => null,
                'equipment_type' => 'monitor',
                'asset_tag' => 'MON-CDMX-044',
                'hostname' => null,
                'assigned_user' => 'Archivo muerto',
                'brand' => 'Acer',
                'model' => 'V226HQL',
                'serial_number' => 'ACR-CDMX-V22-44',
                'cpu' => null,
                'ram_gb' => null,
                'storage_type' => null,
                'storage_gb' => null,
                'operating_system' => null,
                'office_version' => null,
                'purchase_date' => '2021-08-01',
                'warranty_expires_at' => '2024-08-01',
                'status' => 'retired',
                'notes' => 'Pantalla con líneas verticales; solo resguardo documental.',
                'details' => ['size_inches' => 21.5, 'resolution' => 'FHD', 'retirement_reason' => 'Falla de panel'],
            ],
            [
                'branch' => 'Campus Occidente',
                'node' => 'SRV-APP-GDL-01',
                'equipment_type' => 'server',
                'asset_tag' => 'SRV-GDL-APP-01',
                'hostname' => 'SRV-APP-GDL-01',
                'assigned_user' => 'Plataforma Occidente',
                'brand' => 'HPE',
                'model' => 'ProLiant DL360 Gen11',
                'serial_number' => 'HPE-GDL-APP-01',
                'cpu' => '2x Intel Xeon Silver 4510',
                'ram_gb' => 128,
                'storage_type' => 'ssd',
                'storage_gb' => 2048,
                'operating_system' => 'Ubuntu Server 24.04 LTS',
                'office_version' => null,
                'purchase_date' => '2025-02-28',
                'warranty_expires_at' => '2030-02-28',
                'status' => 'in_use',
                'notes' => 'Servidor de aplicaciones regional.',
                'details' => ['rack' => 'RACK-02', 'u_position' => 12, 'idrac' => false, 'ilo' => true],
            ],
            [
                'branch' => 'Campus Occidente',
                'node' => null,
                'equipment_type' => 'headset',
                'asset_tag' => 'DIA-GDL-014',
                'hostname' => null,
                'assigned_user' => 'Contact Center GDL',
                'brand' => 'Poly',
                'model' => 'Blackwire 5220',
                'serial_number' => 'PLY-GDL-5220-14',
                'cpu' => null,
                'ram_gb' => null,
                'storage_type' => null,
                'storage_gb' => null,
                'operating_system' => null,
                'office_version' => null,
                'purchase_date' => '2025-05-06',
                'warranty_expires_at' => '2027-05-06',
                'status' => 'stock',
                'notes' => 'Reserva para onboarding de agentes.',
                'details' => ['noise_cancelling' => true, 'connection' => 'USB-C', 'stock_zone' => 'Bodega TI'],
            ],
        ];

        foreach ($assets as $asset) {
            $branch = $branches->get($asset['branch']);

            if (! $branch) {
                continue;
            }

            $node = $asset['node'] ? $nodes->get($asset['node']) : null;

            ComputerAsset::query()->updateOrCreate(
                [
                    'branch_id' => $branch->id,
                    'asset_tag' => $asset['asset_tag'],
                ],
                [
                    'node_id' => $node?->id,
                    'equipment_type' => $asset['equipment_type'],
                    'hostname' => $asset['hostname'],
                    'assigned_user' => $asset['assigned_user'],
                    'brand' => $asset['brand'],
                    'model' => $asset['model'],
                    'serial_number' => $asset['serial_number'],
                    'cpu' => $asset['cpu'],
                    'ram_gb' => $asset['ram_gb'],
                    'storage_type' => $asset['storage_type'],
                    'storage_gb' => $asset['storage_gb'],
                    'operating_system' => $asset['operating_system'],
                    'office_version' => $asset['office_version'],
                    'purchase_date' => $asset['purchase_date'],
                    'warranty_expires_at' => $asset['warranty_expires_at'],
                    'status' => $asset['status'],
                    'notes' => $asset['notes'],
                    'details' => $asset['details'],
                ]
            );
        }
    }
}